import { Golos_Text } from "next/font/google";
import { Toaster } from "react-hot-toast";

import LayoutClient from "@/components/layout/Layout";

const golos = Golos_Text({ subsets: ["latin"] });

import "./globals.scss";
import ModalProvider from "@/providers/ModalProvider";

const revalidate = 0;

export const metadata = {
  title: "Автопомощь",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ru">
      <body className={golos.className}>
        <LayoutClient>
          <Toaster position="top-center" />
          <ModalProvider />
          {children}
        </LayoutClient>
      </body>
    </html>
  );
}
